// Provider data organized by service ID
export interface ServiceProvider {
  id: string;
  name: string;
  businessName?: string;
  avatar?: string;
  rating: number;
  reviewCount: number;
  description: string;
  priceRange?: { min: number; max: number };
  flatRate?: number;
  hourlyRate?: number;
  completedJobs: number;
  responseTime: string;
  isVerified: boolean;
  isAvailable: boolean;
  location: string;
}

export const providersByService: Record<number, ServiceProvider[]> = {
  // Home Maintenance & Repair Services
  101: [
    // General Plumbing Repair
    {
      id: "p-101-1",
      name: "Juan dela Cruz",
      businessName: "JDC Plumbing Services",
      rating: 4.9,
      reviewCount: 128,
      description: "Licensed plumber with 15+ years experience. Specializing in leak repairs, pipe installation, and emergency plumbing.",
      hourlyRate: 500,
      completedJobs: 342,
      responseTime: "within 30 mins",
      isVerified: true,
      isAvailable: true,
      location: "Makati City",
    },
    {
      id: "p-101-2",
      name: "Pedro Santos",
      rating: 4.7,
      reviewCount: 89,
      description: "Expert in residential and commercial plumbing. Fast, reliable service with warranty on all work.",
      priceRange: { min: 400, max: 800 },
      completedJobs: 215,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Quezon City",
    },
    {
      id: "p-101-3",
      name: "Roberto Aquino",
      businessName: "Aquino Plumbing Solutions",
      rating: 4.8,
      reviewCount: 156,
      description: "Professional plumber. Available 24/7 for emergencies. No job too small or too big.",
      hourlyRate: 450,
      completedJobs: 289,
      responseTime: "within 45 mins",
      isVerified: true,
      isAvailable: false,
      location: "Pasig City",
    },
  ],
  102: [
    // Electrical Repair & Installation
    {
      id: "p-102-1",
      name: "Carlos Reyes",
      businessName: "Reyes Electrical Services",
      rating: 4.9,
      reviewCount: 203,
      description: "Licensed electrician. Expert in wiring, lighting, panel upgrades, and troubleshooting.",
      hourlyRate: 600,
      completedJobs: 478,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Taguig City",
    },
    {
      id: "p-102-2",
      name: "Miguel Torres",
      rating: 4.8,
      reviewCount: 167,
      description: "Certified electrician with 12 years experience. Safe, efficient electrical solutions.",
      priceRange: { min: 500, max: 1200 },
      completedJobs: 356,
      responseTime: "within 2 hours",
      isVerified: true,
      isAvailable: true,
      location: "Mandaluyong",
    },
  ],
  103: [
    // Carpentry & Woodwork
    {
      id: "p-103-1",
      name: "Maria Santos",
      businessName: "MS Carpentry & Woodworks",
      rating: 4.8,
      reviewCount: 95,
      description: "Expert in custom furniture, cabinet making, and wood repairs. 10+ years experience.",
      priceRange: { min: 800, max: 2500 },
      completedJobs: 215,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Quezon City",
    },
    {
      id: "p-103-2",
      name: "Jose Mendoza",
      rating: 4.7,
      reviewCount: 123,
      description: "Skilled carpenter specializing in furniture repair, door installation, and custom woodwork.",
      hourlyRate: 550,
      completedJobs: 267,
      responseTime: "within 2 hours",
      isVerified: true,
      isAvailable: true,
      location: "San Juan",
    },
  ],
  104: [
    // HVAC Maintenance
    {
      id: "p-104-1",
      name: "Carlos Mendoza",
      businessName: "CM HVAC & Aircon Services",
      rating: 4.9,
      reviewCount: 203,
      description: "Certified aircon technician. All brands serviced. Same-day service available.",
      flatRate: 1200,
      completedJobs: 478,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Taguig City",
    },
    {
      id: "p-104-2",
      name: "Randy Gonzales",
      rating: 4.8,
      reviewCount: 178,
      description: "HVAC specialist with 8 years experience. Expert in aircon cleaning, repair, and installation.",
      hourlyRate: 800,
      completedJobs: 389,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Makati City",
    },
  ],
  // Beauty, Wellness & Personal Care
  201: [
    // In-Home Hair Styling
    {
      id: "p-201-1",
      name: "Angela Cruz",
      businessName: "Angela's Beauty Studio",
      rating: 5.0,
      reviewCount: 245,
      description: "Professional hairstylist with 12 years experience. Specializing in balayage and trendy cuts.",
      priceRange: { min: 800, max: 3500 },
      completedJobs: 589,
      responseTime: "within 2 hours",
      isVerified: true,
      isAvailable: true,
      location: "BGC, Taguig",
    },
    {
      id: "p-201-2",
      name: "Jessica Tan",
      rating: 4.9,
      reviewCount: 167,
      description: "Licensed cosmetologist. Expert in hair coloring, highlights, and styling for special events.",
      hourlyRate: 1000,
      completedJobs: 412,
      responseTime: "within 3 hours",
      isVerified: true,
      isAvailable: true,
      location: "Makati City",
    },
  ],
  202: [
    // Mobile Massage Therapy
    {
      id: "p-202-1",
      name: "Michelle Tan",
      businessName: "MT Massage Therapy",
      rating: 4.8,
      reviewCount: 134,
      description: "Licensed massage therapist. Mobile service available. Relaxation guaranteed.",
      hourlyRate: 1000,
      completedJobs: 312,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Mandaluyong City",
    },
    {
      id: "p-202-2",
      name: "Anna Reyes",
      rating: 4.9,
      reviewCount: 201,
      description: "Certified massage therapist specializing in Swedish, deep tissue, and prenatal massage.",
      priceRange: { min: 900, max: 1500 },
      completedJobs: 445,
      responseTime: "within 2 hours",
      isVerified: true,
      isAvailable: true,
      location: "Pasig City",
    },
  ],
  203: [
    // Manicure & Pedicure
    {
      id: "p-203-1",
      name: "Jasmine Lim",
      businessName: "Jasmine's Nail Bar",
      rating: 4.9,
      reviewCount: 178,
      description: "Expert in gel nails, nail art, and pedicure. Using premium products only.",
      priceRange: { min: 350, max: 1500 },
      completedJobs: 425,
      responseTime: "within 30 mins",
      isVerified: true,
      isAvailable: true,
      location: "Alabang, Muntinlupa",
    },
  ],
  // Education & Professional Services
  301: [
    // Private Tutoring (Math)
    {
      id: "p-301-1",
      name: "Prof. David Garcia",
      rating: 4.9,
      reviewCount: 156,
      description: "Former university professor. Specializing in Calculus, Statistics, and Algebra.",
      hourlyRate: 600,
      completedJobs: 267,
      responseTime: "within 3 hours",
      isVerified: true,
      isAvailable: true,
      location: "Quezon City",
    },
    {
      id: "p-301-2",
      name: "Maria Lopez",
      rating: 4.8,
      reviewCount: 134,
      description: "Math tutor for high school and college students. Patient and effective teaching methods.",
      hourlyRate: 500,
      completedJobs: 198,
      responseTime: "within 4 hours",
      isVerified: true,
      isAvailable: true,
      location: "Manila",
    },
  ],
  302: [
    // Language Lessons
    {
      id: "p-302-1",
      name: "Sarah Alvarez",
      businessName: "English Excellence Academy",
      rating: 5.0,
      reviewCount: 201,
      description: "TESOL certified. 8 years teaching experience. IELTS prep expert.",
      hourlyRate: 700,
      completedJobs: 412,
      responseTime: "within 2 hours",
      isVerified: true,
      isAvailable: true,
      location: "Ortigas, Pasig",
    },
  ],
  303: [
    // Music Lessons
    {
      id: "p-303-1",
      name: "Miguel Santos",
      businessName: "Piano Lessons by Miguel",
      rating: 4.8,
      reviewCount: 89,
      description: "Classical and contemporary piano instructor. All ages welcome.",
      priceRange: { min: 800, max: 1500 },
      completedJobs: 178,
      responseTime: "within 4 hours",
      isVerified: true,
      isAvailable: true,
      location: "Makati City",
    },
  ],
  // Domestic & Cleaning Services
  401: [
    // Deep House Cleaning
    {
      id: "p-401-1",
      name: "Rosa Magpantay",
      businessName: "Sparkle Clean PH",
      rating: 4.9,
      reviewCount: 312,
      description: "Professional cleaning team. Eco-friendly products. 100% satisfaction guarantee.",
      flatRate: 1800,
      completedJobs: 687,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Metro Manila (All Areas)",
    },
    {
      id: "p-401-2",
      name: "Maria Bautista",
      rating: 4.8,
      reviewCount: 234,
      description: "Expert deep cleaning service. Professional team with all equipment provided.",
      priceRange: { min: 1500, max: 2500 },
      completedJobs: 512,
      responseTime: "within 2 hours",
      isVerified: true,
      isAvailable: true,
      location: "Quezon City",
    },
  ],
  402: [
    // Regular Housekeeping
    {
      id: "p-402-1",
      name: "Linda Cruz",
      rating: 4.7,
      reviewCount: 189,
      description: "Reliable housekeeping service. Weekly or bi-weekly schedules available.",
      hourlyRate: 400,
      completedJobs: 456,
      responseTime: "within 3 hours",
      isVerified: true,
      isAvailable: true,
      location: "Makati & BGC",
    },
  ],
  // Pet Services
  501: [
    // Dog Walking
    {
      id: "p-501-1",
      name: "Mark Rivera",
      businessName: "Happy Tails Pet Sitting",
      rating: 4.9,
      reviewCount: 178,
      description: "Reliable pet sitter. Daily updates with photos. Your pets will love me!",
      hourlyRate: 300,
      completedJobs: 389,
      responseTime: "within 30 mins",
      isVerified: true,
      isAvailable: true,
      location: "BGC & Makati",
    },
  ],
  503: [
    // Pet Grooming
    {
      id: "p-503-1",
      name: "Patricia Cruz",
      businessName: "Pawfect Care PH",
      rating: 5.0,
      reviewCount: 234,
      description: "Certified pet groomer. Gentle handling. All breeds welcome.",
      priceRange: { min: 500, max: 1500 },
      completedJobs: 512,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Quezon City",
    },
  ],
  // Events & Entertainment
  601: [
    // DJ Services
    {
      id: "p-601-1",
      name: "DJ Paolo",
      businessName: "Paolo Events & Entertainment",
      rating: 4.8,
      reviewCount: 156,
      description: "10+ years experience. All event types. Premium sound system included.",
      priceRange: { min: 5000, max: 15000 },
      completedJobs: 234,
      responseTime: "within 3 hours",
      isVerified: true,
      isAvailable: true,
      location: "Metro Manila",
    },
  ],
  602: [
    // Event Photography
    {
      id: "p-602-1",
      name: "Carla Dizon",
      businessName: "Capture Moments Photography",
      rating: 5.0,
      reviewCount: 289,
      description: "Award-winning photographer. Creative shots. Fast turnaround on edited photos.",
      priceRange: { min: 8000, max: 25000 },
      completedJobs: 412,
      responseTime: "within 4 hours",
      isVerified: true,
      isAvailable: true,
      location: "Nationwide",
    },
  ],
  // Automotive & Tech Support
  701: [
    // Mobile Car Wash & Detailing
    {
      id: "p-701-1",
      name: "Tony Mercado",
      businessName: "AutoCare Mobile Service",
      rating: 4.9,
      reviewCount: 267,
      description: "Professional car care at your location. Waterless option available.",
      priceRange: { min: 800, max: 2500 },
      completedJobs: 589,
      responseTime: "within 1 hour",
      isVerified: true,
      isAvailable: true,
      location: "Metro Manila",
    },
  ],
  704: [
    // Computer Repair
    {
      id: "p-704-1",
      name: "Ryan Baltazar",
      businessName: "Tech Solutions PH",
      rating: 4.8,
      reviewCount: 198,
      description: "Certified technician. Fast repair service. 90-day warranty on all repairs.",
      flatRate: 1200,
      completedJobs: 445,
      responseTime: "within 2 hours",
      isVerified: true,
      isAvailable: true,
      location: "Ortigas & Makati",
    },
  ],
};

// Service details mapping
export const serviceDetails: Record<number, { title: string; category: string }> = {
  101: { title: "General Plumbing Repair", category: "Home Maintenance & Repair" },
  102: { title: "Electrical Repair & Installation", category: "Home Maintenance & Repair" },
  103: { title: "Carpentry & Woodwork", category: "Home Maintenance & Repair" },
  104: { title: "HVAC Maintenance", category: "Home Maintenance & Repair" },
  105: { title: "Roof Inspection & Repair", category: "Home Maintenance & Repair" },
  106: { title: "Door & Window Repair", category: "Home Maintenance & Repair" },
  107: { title: "Drywall Patching", category: "Home Maintenance & Repair" },
  108: { title: "Gutter Cleaning & Repair", category: "Home Maintenance & Repair" },
  201: { title: "In-Home Hair Styling", category: "Beauty, Wellness & Personal Care" },
  202: { title: "Mobile Massage Therapy", category: "Beauty, Wellness & Personal Care" },
  203: { title: "Manicure & Pedicure", category: "Beauty, Wellness & Personal Care" },
  204: { title: "Makeup Artist Services", category: "Beauty, Wellness & Personal Care" },
  205: { title: "Personal Training", category: "Beauty, Wellness & Personal Care" },
  206: { title: "Yoga Instruction", category: "Beauty, Wellness & Personal Care" },
  207: { title: "Nutrition Consulting", category: "Beauty, Wellness & Personal Care" },
  301: { title: "Private Tutoring (Math)", category: "Education & Professional Services" },
  302: { title: "Language Lessons", category: "Education & Professional Services" },
  303: { title: "Music Lessons", category: "Education & Professional Services" },
  304: { title: "Resume Writing", category: "Education & Professional Services" },
  305: { title: "Business Consulting", category: "Education & Professional Services" },
  306: { title: "Tax Preparation", category: "Education & Professional Services" },
  307: { title: "Legal Consultation", category: "Education & Professional Services" },
  308: { title: "Career Coaching", category: "Education & Professional Services" },
  401: { title: "Deep House Cleaning", category: "Domestic & Cleaning Services" },
  402: { title: "Regular Housekeeping", category: "Domestic & Cleaning Services" },
  403: { title: "Carpet & Upholstery Cleaning", category: "Domestic & Cleaning Services" },
  404: { title: "Window Washing", category: "Domestic & Cleaning Services" },
  405: { title: "Move-In/Move-Out Cleaning", category: "Domestic & Cleaning Services" },
  406: { title: "Laundry & Ironing", category: "Domestic & Cleaning Services" },
  407: { title: "Kitchen Deep Clean", category: "Domestic & Cleaning Services" },
  408: { title: "Bathroom Sanitization", category: "Domestic & Cleaning Services" },
  501: { title: "Dog Walking", category: "Pet Services" },
  502: { title: "Pet Sitting", category: "Pet Services" },
  503: { title: "Pet Grooming", category: "Pet Services" },
  504: { title: "Pet Training", category: "Pet Services" },
  505: { title: "Veterinary House Calls", category: "Pet Services" },
  506: { title: "Aquarium Maintenance", category: "Pet Services" },
  507: { title: "Pet Taxi Service", category: "Pet Services" },
  601: { title: "DJ Services", category: "Events & Entertainment" },
  602: { title: "Event Photography", category: "Events & Entertainment" },
  603: { title: "Catering Services", category: "Events & Entertainment" },
  604: { title: "Party Planning", category: "Events & Entertainment" },
  605: { title: "Face Painting", category: "Events & Entertainment" },
  606: { title: "Balloon Decoration", category: "Events & Entertainment" },
  607: { title: "Magic Shows", category: "Events & Entertainment" },
  608: { title: "Live Band Performance", category: "Events & Entertainment" },
  701: { title: "Mobile Car Wash & Detailing", category: "Automotive & Tech Support" },
  702: { title: "Oil Change Service", category: "Automotive & Tech Support" },
  703: { title: "Tire Replacement", category: "Automotive & Tech Support" },
  704: { title: "Computer Repair", category: "Automotive & Tech Support" },
  705: { title: "Phone Screen Replacement", category: "Automotive & Tech Support" },
  706: { title: "Home Network Setup", category: "Automotive & Tech Support" },
  707: { title: "Smart Home Installation", category: "Automotive & Tech Support" },
  708: { title: "TV Mounting & Setup", category: "Automotive & Tech Support" },
};
